name: model_usage_demo_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # tflite: ^1.1.2
  image_picker: ^0.8.3+2
  tflite_flutter: ^0.10.4
  tflite_v2: ^1.0.0
  sqflite: ^2.3.2
  path: ^1.9.0
  geolocator: ^11.0.0
  geocoding: ^2.2.0
  maps_launcher: ^2.2.1
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  random_string: ^2.3.1
  google_maps_flutter: ^2.6.0
  # geolocator: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/
